pde: burgers

train:
  trainer: autoscale
  iterations: 500
  num_domain: 100
  num_bc: 2000
  learning_rate: 1e-3
  hidden_layers: 8
  hidden_units: 128
  out_dir: experiments

eval:
  n_test: 10000
