device: cuda
out_ckpt: checkpoints/darcy_fno64.pt

data:
  n_train: 1000
  batch_size: 32
  test_res: [16]
  n_tests:  [100]

model:
  width: 64
  modes_h: 16
  modes_w: 16

optim:
  lr: 8e-3
  t_max: 30

training:
  epochs: 20
  eval_every: 1
